config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', registration: 'register'}
  root "posts#index"
  resources :posts, only: [:new, :create, :index]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @messages = Post.all
  end

  def new
    @message = Post.new
  end

  def create
    @message = current_user.posts.build(post_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to posts_path, notice: 'Your message was successfully posted.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @message = Post.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Your message was successfully destroyed.' }
    end
  end

  def post_params
    params.require(:post).permit(:title, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
  </div>
  <div>
   <% if current_user %>
    <%= link_to 'Log-Out', destroy_user_session_path, :method => :delete %>
    <% else %>
    <%= link_to 'Sign-Up', new_user_registration_path %><br>
    <%= link_to 'Log-In', new_user_session_path %><br>
   <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p>if you are logged in, you can create an article <%= link_to 'here', new_post_path %>

<% @messages.each do |msg| %>
  <h3><%= msg.title%></h3>
  <p><%= msg.message %></p>
  <em><%= msg.user.name if user_signed_in?  %><em>
<% end %>

app/views/posts/new.html.erb
<h2>Create a new Message Here</h2>

<%= form_with(model: @message, local: true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <p>
        <%=form.label :title %><br>
        <%=form.text_field :title, placeholder: 'Your title'%>
    </p>
    <p>
        <%=form.label :message %><br>
        <%=form.text_area :message, placeholder: 'Write your message Here', size: "60x12" %>
    </p>

    <p>
        <%=form.submit%>
    </p>
<% end %>